package mnj.mfg.model.services.client;

import mnj.mfg.model.services.common.AppModule;

import oracle.jbo.client.remote.ApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Aug 16 11:07:05 BDT 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AppModuleClient extends ApplicationModuleImpl implements AppModule {
    /**
     * This is the default constructor (do not remove).
     */
    public AppModuleClient() {
    }


//    public void validateIssueRecDate() {
//        Object _ret =
//            this.riInvokeExportedMethod(this,"validateIssueRecDate",null,null);
//        return;
//    }


    public void fetchMethod(String lineId) {
        Object _ret =
            this.riInvokeExportedMethod(this,"fetchMethod",new String [] {"java.lang.String"},new Object[] {lineId});
        return;
    }

    public void copyMethod(String stn) {
        Object _ret =
            this.riInvokeExportedMethod(this,"copyMethod",new String [] {"java.lang.String"},new Object[] {stn});
        return;
    }

    public void populateOperations() {
        Object _ret =
            this.riInvokeExportedMethod(this,"populateOperations",null,null);
        return;
    }

    public void WhereClauseSubProcess() {
        Object _ret =
            this.riInvokeExportedMethod(this,"WhereClauseSubProcess",null,null);
        return;
    }

    public void populateSubProcess() {
        Object _ret =
            this.riInvokeExportedMethod(this,"populateSubProcess",null,null);
        return;
    }

    public int VersionCreation() {
        Object _ret =
            this.riInvokeExportedMethod(this,"VersionCreation",null,null);
        return ((Integer)_ret).intValue();
    }

    public void popupDeselectActionListener() {
        Object _ret =
            this.riInvokeExportedMethod(this,"popupDeselectActionListener",null,null);
        return;
    }

    public void popupSelectActionListener() {
        Object _ret =
            this.riInvokeExportedMethod(this,"popupSelectActionListener",null,null);
        return;
    }

    public void Delete_Header() {
        Object _ret = this.riInvokeExportedMethod(this,"Delete_Header",null,null);
        return;
    }

    public void Commit() {
        Object _ret = this.riInvokeExportedMethod(this,"Commit",null,null);
        return;
    }

    public void Copy_Fields_To_Lines(String PerBatchQty,
                                     String NumberOfBatches) {
        Object _ret =
            this.riInvokeExportedMethod(this,"Copy_Fields_To_Lines",new String [] {"java.lang.String","java.lang.String"},new Object[] {PerBatchQty, NumberOfBatches});
        return;
    }

    public void ReCalculate_Fields() {
        Object _ret =
            this.riInvokeExportedMethod(this,"ReCalculate_Fields",null,null);
        return;
    }

    public void setSessionValues(String orgId, String userId, String respId,
                                 String respAppl) {
        Object _ret =
            this.riInvokeExportedMethod(this,"setSessionValues",new String [] {"java.lang.String","java.lang.String","java.lang.String","java.lang.String"},new Object[] {orgId, userId, respId, respAppl});
        return;
    }

    public void Qty_Calculation() {
        Object _ret =
            this.riInvokeExportedMethod(this,"Qty_Calculation",null,null);
        return;
    }

    public void Fabric_Type_H() {
        Object _ret = this.riInvokeExportedMethod(this,"Fabric_Type_H",null,null);
        return;
    }

    public void DeleteSubProcess() {
        Object _ret =
            this.riInvokeExportedMethod(this,"DeleteSubProcess",null,null);
        return;
    }

    public void DeleteOperations() {
        Object _ret =
            this.riInvokeExportedMethod(this,"DeleteOperations",null,null);
        return;
    }

    public void DeleteChemicals() {
        Object _ret =
            this.riInvokeExportedMethod(this,"DeleteChemicals",null,null);
        return;
    }

    public String validateIssueRecDate() {
        Object _ret =
            this.riInvokeExportedMethod(this,"validateIssueRecDate",null,null);
        return (String)_ret;
    }

    public int CopyCreation() {
        Object _ret = this.riInvokeExportedMethod(this,"CopyCreation",null,null);
        return ((Integer)_ret).intValue();
    }
}
