package mnj.mfg.model.views;

import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Nov 06 15:10:45 PKT 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DetailPopUpRowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        DetailId {
            public Object get(DetailPopUpRowImpl obj) {
                return obj.getDetailId();
            }

            public void put(DetailPopUpRowImpl obj, Object value) {
                obj.setDetailId((Number)value);
            }
        }
        ,
        LineId {
            public Object get(DetailPopUpRowImpl obj) {
                return obj.getLineId();
            }

            public void put(DetailPopUpRowImpl obj, Object value) {
                obj.setLineId((Number)value);
            }
        }
        ,
        InventoryItemId {
            public Object get(DetailPopUpRowImpl obj) {
                return obj.getInventoryItemId();
            }

            public void put(DetailPopUpRowImpl obj, Object value) {
                obj.setInventoryItemId((Number)value);
            }
        }
        ,
        Uom {
            public Object get(DetailPopUpRowImpl obj) {
                return obj.getUom();
            }

            public void put(DetailPopUpRowImpl obj, Object value) {
                obj.setUom((String)value);
            }
        }
        ,
        PerBatchQty {
            public Object get(DetailPopUpRowImpl obj) {
                return obj.getPerBatchQty();
            }

            public void put(DetailPopUpRowImpl obj, Object value) {
                obj.setPerBatchQty((Number)value);
            }
        }
        ,
        PerBatchCons {
            public Object get(DetailPopUpRowImpl obj) {
                return obj.getPerBatchCons();
            }

            public void put(DetailPopUpRowImpl obj, Object value) {
                obj.setPerBatchCons((Number)value);
            }
        }
        ,
        ItemCode {
            public Object get(DetailPopUpRowImpl obj) {
                return obj.getItemCode();
            }

            public void put(DetailPopUpRowImpl obj, Object value) {
                obj.setItemCode((String)value);
            }
        }
        ,
        Description {
            public Object get(DetailPopUpRowImpl obj) {
                return obj.getDescription();
            }

            public void put(DetailPopUpRowImpl obj, Object value) {
                obj.setDescription((String)value);
            }
        }
        ,
        TotalCons {
            public Object get(DetailPopUpRowImpl obj) {
                return obj.getTotalCons();
            }

            public void put(DetailPopUpRowImpl obj, Object value) {
                obj.setTotalCons((Number)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(DetailPopUpRowImpl object);

        public abstract void put(DetailPopUpRowImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int DETAILID = AttributesEnum.DetailId.index();
    public static final int LINEID = AttributesEnum.LineId.index();
    public static final int INVENTORYITEMID = AttributesEnum.InventoryItemId.index();
    public static final int UOM = AttributesEnum.Uom.index();
    public static final int PERBATCHQTY = AttributesEnum.PerBatchQty.index();
    public static final int PERBATCHCONS = AttributesEnum.PerBatchCons.index();
    public static final int ITEMCODE = AttributesEnum.ItemCode.index();
    public static final int DESCRIPTION = AttributesEnum.Description.index();
    public static final int TOTALCONS = AttributesEnum.TotalCons.index();

    /**
     * This is the default constructor (do not remove).
     */
    public DetailPopUpRowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute DetailId.
     * @return the DetailId
     */
    public Number getDetailId() {
        return (Number) getAttributeInternal(DETAILID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute DetailId.
     * @param value value to set the  DetailId
     */
    public void setDetailId(Number value) {
        setAttributeInternal(DETAILID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute LineId.
     * @return the LineId
     */
    public Number getLineId() {
        return (Number) getAttributeInternal(LINEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute LineId.
     * @param value value to set the  LineId
     */
    public void setLineId(Number value) {
        setAttributeInternal(LINEID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute InventoryItemId.
     * @return the InventoryItemId
     */
    public Number getInventoryItemId() {
        return (Number) getAttributeInternal(INVENTORYITEMID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute InventoryItemId.
     * @param value value to set the  InventoryItemId
     */
    public void setInventoryItemId(Number value) {
        setAttributeInternal(INVENTORYITEMID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Uom.
     * @return the Uom
     */
    public String getUom() {
        return (String) getAttributeInternal(UOM);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Uom.
     * @param value value to set the  Uom
     */
    public void setUom(String value) {
        setAttributeInternal(UOM, value);
    }

    /**
     * Gets the attribute value for the calculated attribute PerBatchQty.
     * @return the PerBatchQty
     */
    public Number getPerBatchQty() {
        return (Number) getAttributeInternal(PERBATCHQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute PerBatchQty.
     * @param value value to set the  PerBatchQty
     */
    public void setPerBatchQty(Number value) {
        setAttributeInternal(PERBATCHQTY, value);
    }

    /**
     * Gets the attribute value for the calculated attribute PerBatchCons.
     * @return the PerBatchCons
     */
    public Number getPerBatchCons() {
        return (Number) getAttributeInternal(PERBATCHCONS);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute PerBatchCons.
     * @param value value to set the  PerBatchCons
     */
    public void setPerBatchCons(Number value) {
        setAttributeInternal(PERBATCHCONS, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ItemCode.
     * @return the ItemCode
     */
    public String getItemCode() {
        return (String) getAttributeInternal(ITEMCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ItemCode.
     * @param value value to set the  ItemCode
     */
    public void setItemCode(String value) {
        setAttributeInternal(ITEMCODE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Description.
     * @return the Description
     */
    public String getDescription() {
        return (String) getAttributeInternal(DESCRIPTION);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Description.
     * @param value value to set the  Description
     */
    public void setDescription(String value) {
        setAttributeInternal(DESCRIPTION, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TotalCons.
     * @return the TotalCons
     */
    public Number getTotalCons() {
        return (Number) getAttributeInternal(TOTALCONS);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TotalCons.
     * @param value value to set the  TotalCons
     */
    public void setTotalCons(Number value) {
        setAttributeInternal(TOTALCONS, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
