package mnj.mfg.model.views;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Nov 06 15:10:45 PKT 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DetailPopUpImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public DetailPopUpImpl() {
    }
}
