package mnj.mfg.model.views;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Nov 06 15:10:02 PKT 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class LinePopUpImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public LinePopUpImpl() {
    }
}
