package mnj.mfg.model.views;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Apr 17 12:12:22 PKT 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class MnjMfgSubProcessVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public MnjMfgSubProcessVOImpl() {
    }
}
