package mnj.mfg.model.views;

import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Nov 06 16:37:21 PKT 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PopulateOpRowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        SaleOrderId {
            public Object get(PopulateOpRowImpl obj) {
                return obj.getSaleOrderId();
            }

            public void put(PopulateOpRowImpl obj, Object value) {
                obj.setSaleOrderId((Number)value);
            }
        }
        ,
        SaleOrderLineId {
            public Object get(PopulateOpRowImpl obj) {
                return obj.getSaleOrderLineId();
            }

            public void put(PopulateOpRowImpl obj, Object value) {
                obj.setSaleOrderLineId((Number)value);
            }
        }
        ,
        StnNo {
            public Object get(PopulateOpRowImpl obj) {
                return obj.getStnNo();
            }

            public void put(PopulateOpRowImpl obj, Object value) {
                obj.setStnNo((String)value);
            }
        }
        ,
        MinorOperation {
            public Object get(PopulateOpRowImpl obj) {
                return obj.getMinorOperation();
            }

            public void put(PopulateOpRowImpl obj, Object value) {
                obj.setMinorOperation((String)value);
            }
        }
        ,
        MajorOpId {
            public Object get(PopulateOpRowImpl obj) {
                return obj.getMajorOpId();
            }

            public void put(PopulateOpRowImpl obj, Object value) {
                obj.setMajorOpId((Number)value);
            }
        }
        ,
        Smv {
            public Object get(PopulateOpRowImpl obj) {
                return obj.getSmv();
            }

            public void put(PopulateOpRowImpl obj, Object value) {
                obj.setSmv((Number)value);
            }
        }
        ,
        OperationDescription {
            public Object get(PopulateOpRowImpl obj) {
                return obj.getOperationDescription();
            }

            public void put(PopulateOpRowImpl obj, Object value) {
                obj.setOperationDescription((String)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(PopulateOpRowImpl object);

        public abstract void put(PopulateOpRowImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int SALEORDERID = AttributesEnum.SaleOrderId.index();
    public static final int SALEORDERLINEID = AttributesEnum.SaleOrderLineId.index();
    public static final int STNNO = AttributesEnum.StnNo.index();
    public static final int MINOROPERATION = AttributesEnum.MinorOperation.index();
    public static final int MAJOROPID = AttributesEnum.MajorOpId.index();
    public static final int SMV = AttributesEnum.Smv.index();
    public static final int OPERATIONDESCRIPTION = AttributesEnum.OperationDescription.index();

    /**
     * This is the default constructor (do not remove).
     */
    public PopulateOpRowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute SaleOrderId.
     * @return the SaleOrderId
     */
    public Number getSaleOrderId() {
        return (Number) getAttributeInternal(SALEORDERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute SaleOrderId.
     * @param value value to set the  SaleOrderId
     */
    public void setSaleOrderId(Number value) {
        setAttributeInternal(SALEORDERID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute SaleOrderLineId.
     * @return the SaleOrderLineId
     */
    public Number getSaleOrderLineId() {
        return (Number) getAttributeInternal(SALEORDERLINEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute SaleOrderLineId.
     * @param value value to set the  SaleOrderLineId
     */
    public void setSaleOrderLineId(Number value) {
        setAttributeInternal(SALEORDERLINEID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute StnNo.
     * @return the StnNo
     */
    public String getStnNo() {
        return (String) getAttributeInternal(STNNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute StnNo.
     * @param value value to set the  StnNo
     */
    public void setStnNo(String value) {
        setAttributeInternal(STNNO, value);
    }

    /**
     * Gets the attribute value for the calculated attribute MinorOperation.
     * @return the MinorOperation
     */
    public String getMinorOperation() {
        return (String) getAttributeInternal(MINOROPERATION);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute MinorOperation.
     * @param value value to set the  MinorOperation
     */
    public void setMinorOperation(String value) {
        setAttributeInternal(MINOROPERATION, value);
    }

    /**
     * Gets the attribute value for the calculated attribute MajorOpId.
     * @return the MajorOpId
     */
    public Number getMajorOpId() {
        return (Number) getAttributeInternal(MAJOROPID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute MajorOpId.
     * @param value value to set the  MajorOpId
     */
    public void setMajorOpId(Number value) {
        setAttributeInternal(MAJOROPID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Smv.
     * @return the Smv
     */
    public Number getSmv() {
        return (Number) getAttributeInternal(SMV);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Smv.
     * @param value value to set the  Smv
     */
    public void setSmv(Number value) {
        setAttributeInternal(SMV, value);
    }

    /**
     * Gets the attribute value for the calculated attribute OperationDescription.
     * @return the OperationDescription
     */
    public String getOperationDescription() {
        return (String) getAttributeInternal(OPERATIONDESCRIPTION);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute OperationDescription.
     * @param value value to set the  OperationDescription
     */
    public void setOperationDescription(String value) {
        setAttributeInternal(OPERATIONDESCRIPTION, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
