package mnj.mfg.model.views;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Nov 07 14:23:53 BDT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SubProcessPopUpImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public SubProcessPopUpImpl() {
    }
}
