package mnj.mfg.model.services.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Aug 16 11:07:05 BDT 2015
// ---------------------------------------------------------------------
public interface AppModule extends ApplicationModule {
    void fetchMethod(String lineId);

    void copyMethod(String stn);

    void populateOperations();

    void WhereClauseSubProcess();

    void populateSubProcess();

    int VersionCreation();

    void popupDeselectActionListener();

    void popupSelectActionListener();

    void Delete_Header();

    void Commit();

    void Copy_Fields_To_Lines(String PerBatchQty, String NumberOfBatches);

    void ReCalculate_Fields();

    void setSessionValues(String orgId, String userId, String respId,
                          String respAppl);

    void Qty_Calculation();

    void Fabric_Type_H();

    void DeleteSubProcess();

    void DeleteOperations();

    void DeleteChemicals();

    String validateIssueRecDate();

    int CopyCreation();
}
