package mnj.mfg.model.entities;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Dec 06 16:39:51 BDT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class MnjMfgShadeLImpl extends EntityImpl {
    private static EntityDefImpl mDefinitionObject;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        ShadeLineId {
            public Object get(MnjMfgShadeLImpl obj) {
                return obj.getShadeLineId();
            }

            public void put(MnjMfgShadeLImpl obj, Object value) {
                obj.setShadeLineId((Number)value);
            }
        }
        ,
        HeaderId {
            public Object get(MnjMfgShadeLImpl obj) {
                return obj.getHeaderId();
            }

            public void put(MnjMfgShadeLImpl obj, Object value) {
                obj.setHeaderId((Number)value);
            }
        }
        ,
        Shades {
            public Object get(MnjMfgShadeLImpl obj) {
                return obj.getShades();
            }

            public void put(MnjMfgShadeLImpl obj, Object value) {
                obj.setShades((String)value);
            }
        }
        ,
        MnjMfgWashRecipeH {
            public Object get(MnjMfgShadeLImpl obj) {
                return obj.getMnjMfgWashRecipeH();
            }

            public void put(MnjMfgShadeLImpl obj, Object value) {
                obj.setMnjMfgWashRecipeH((MnjMfgWashRecipeHImpl)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(MnjMfgShadeLImpl object);

        public abstract void put(MnjMfgShadeLImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }

    public static final int SHADELINEID = AttributesEnum.ShadeLineId.index();
    public static final int HEADERID = AttributesEnum.HeaderId.index();
    public static final int SHADES = AttributesEnum.Shades.index();
    public static final int MNJMFGWASHRECIPEH = AttributesEnum.MnjMfgWashRecipeH.index();

    /**
     * This is the default constructor (do not remove).
     */
    public MnjMfgShadeLImpl() {
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = EntityDefImpl.findDefObject("mnj.mfg.model.entities.MnjMfgShadeL");
        }
        return mDefinitionObject;
    }

    /**
     * Gets the attribute value for ShadeLineId, using the alias name ShadeLineId.
     * @return the ShadeLineId
     */
    public Number getShadeLineId() {
        return (Number)getAttributeInternal(SHADELINEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for ShadeLineId.
     * @param value value to set the ShadeLineId
     */
    public void setShadeLineId(Number value) {
        setAttributeInternal(SHADELINEID, value);
    }

    /**
     * Gets the attribute value for HeaderId, using the alias name HeaderId.
     * @return the HeaderId
     */
    public Number getHeaderId() {
        return (Number)getAttributeInternal(HEADERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for HeaderId.
     * @param value value to set the HeaderId
     */
    public void setHeaderId(Number value) {
        setAttributeInternal(HEADERID, value);
    }

    /**
     * Gets the attribute value for Shades, using the alias name Shades.
     * @return the Shades
     */
    public String getShades() {
        return (String)getAttributeInternal(SHADES);
    }

    /**
     * Sets <code>value</code> as the attribute value for Shades.
     * @param value value to set the Shades
     */
    public void setShades(String value) {
        setAttributeInternal(SHADES, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }

    /**
     * @return the associated entity MnjMfgWashRecipeHImpl.
     */
    public MnjMfgWashRecipeHImpl getMnjMfgWashRecipeH() {
        return (MnjMfgWashRecipeHImpl)getAttributeInternal(MNJMFGWASHRECIPEH);
    }

    /**
     * Sets <code>value</code> as the associated entity MnjMfgWashRecipeHImpl.
     */
    public void setMnjMfgWashRecipeH(MnjMfgWashRecipeHImpl value) {
        setAttributeInternal(MNJMFGWASHRECIPEH, value);
    }

    /**
     * @param shadeLineId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Number shadeLineId) {
        return new Key(new Object[]{shadeLineId});
    }
       
        protected void create(AttributeList attributeList) {
            super.create(attributeList);
    oracle.jbo.server.SequenceImpl s =new oracle.jbo.server.SequenceImpl("MNJ_MFG_WASH_RECIPE_SHADE_S",getDBTransaction());
    oracle.jbo.domain.Number sVal = s.getSequenceNumber();
    setShadeLineId(sVal);
    }
}
