package mnj.mfg.model.services;

import mnj.mfg.model.lov.views.OperationsPopUpVOImpl;
import mnj.mfg.model.services.common.AppModule;

import mnj.mfg.model.views.DetailPopUpImpl;
import mnj.mfg.model.views.HederPopUpImpl;
import mnj.mfg.model.views.LinePopUpImpl;
import mnj.mfg.model.views.MnjMfgSubProcessVOImpl;
import mnj.mfg.model.views.MnjMfgWashRecipeDViewImpl;
import mnj.mfg.model.views.MnjMfgWashRecipeLViewImpl;

import mnj.mfg.model.views.PopulateOpImpl;

import mnj.mfg.model.views.SubProcessPopUpImpl;

import oracle.jbo.Row;
import oracle.jbo.RowSet;
import oracle.jbo.RowSetIterator;
import oracle.jbo.ViewObject;
import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewLinkImpl;
import oracle.jbo.server.ViewObjectImpl;

import oracle.jdbc.OracleTypes;

import java.sql.CallableStatement;
import java.sql.SQLException;

import java.text.DateFormat;

import java.text.ParseException;
import java.text.SimpleDateFormat;

import java.util.Date;
import java.util.Map;

import javax.faces.application.FacesMessage;
import javax.faces.context.ExternalContext;
import javax.faces.context.FacesContext;

import javax.servlet.http.HttpSession;

import mnj.mfg.model.views.MnjMfgSubProcessVORowImpl;
import mnj.mfg.model.views.MnjMfgWashRecipeDViewRowImpl;
import mnj.mfg.model.views.MnjMfgWashRecipeLViewRowImpl;

import oracle.adf.share.ADFContext;

import oracle.jbo.JboException;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Aug 16 10:54:10 BDT 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AppModuleImpl extends ApplicationModuleImpl implements AppModule {
    /**
     * This is the default constructor (do not remove).
     */
    public static final int VARCHAR2 = OracleTypes.NUMBER;
    public static final int INTEGER = OracleTypes.INTEGER;

    public AppModuleImpl() {
    }

    /**
     * Container's getter for MnjMfgWashRecipeHView1.
     * @return MnjMfgWashRecipeHView1
     */
    public ViewObjectImpl getMnjMfgWashRecipeHView1() {
        return (ViewObjectImpl)findViewObject("MnjMfgWashRecipeHView1");
    }

    /**
     * Container's getter for MnjMfgWashRecipeLView1.
     * @return MnjMfgWashRecipeLView1
     */
    public ViewObjectImpl getMnjMfgWashRecipeLView1() {
        return (ViewObjectImpl)findViewObject("MnjMfgWashRecipeLView1");
    }

    /**
     * Container's getter for MnjMfgWashRecipeDView1.
     * @return MnjMfgWashRecipeDView1
     */
    public ViewObjectImpl getMnjMfgWashRecipeDView1() {
        return (ViewObjectImpl)findViewObject("MnjMfgWashRecipeDView1");
    }


    /**
     * Container's getter for MnjMfgWashRecipeLFkLink1.
     * @return MnjMfgWashRecipeLFkLink1
     */
    public ViewLinkImpl getMnjMfgWashRecipeLFkLink1() {
        return (ViewLinkImpl)findViewLink("MnjMfgWashRecipeLFkLink1");
    }

    /**
     * Container's getter for MnjMfgWashRecipeDFkLink1.
     * @return MnjMfgWashRecipeDFkLink1
     */
    public ViewLinkImpl getMnjMfgWashRecipeDFkLink1() {
        return (ViewLinkImpl)findViewLink("MnjMfgWashRecipeDFkLink1");
    }

    public void Commit() {
        getDBTransaction().commit();
    }

    public void fetchMethod(String lineId) {


        ViewObject populatevo = getPopulateOp1();
        populatevo.setWhereClause("STN_NO = '" + lineId + "'");
        populatevo.executeQuery();


        if (populatevo.getRowCount() == 0)
            ;
        RowSetIterator it = populatevo.createRowSetIterator("aa");

        while (it.hasNext()) {

            Row r = it.next();
            populateLines(r);
        }

        it.closeRowSetIterator();
    }

    public void populateLines(Row poprow) {

        Row linerow = createLines();

        linerow.setAttribute("MinorOperations",
                             getPopulateValue(poprow, "MinorOperation"));
        linerow.setAttribute("MajorOperations",
                             getPopulateValue(poprow, "OperationDescription"));
        linerow.setAttribute("MajorOpId",
                             getPopulateValue(poprow, "MajorOpId"));
        linerow.setAttribute("Smv", getPopulateValue(poprow, "Smv"));


    } //end of populateLines

    //    public Row createLines() {
    //
    //        ViewObject vo = getMnjMfgWashRecipeLView1();
    //        Row row = vo.createRow();
    //        vo.insertRow(row);
    //        row.setNewRowState(Row.STATUS_INITIALIZED);
    //        return row;
    //    } //end of createHeader

    public String getPopulateValue(Row r, String columnName) {

        String value = null;
        try {
            value = r.getAttribute(columnName).toString();
        } catch (Exception e) {
            ;
        }
        return value;
    }

    public void copyMethod(String stn) {

        System.out.println("STN AM copy --->" + stn);
        ViewObject hvo = getHederPopUp1();
        hvo.setWhereClause("HEADER_ID = " + stn);
        hvo.executeQuery();

        System.out.println("After header execute--->");

        RowSetIterator it = hvo.createRowSetIterator("hit");
        String headerId = null;
        while (it.hasNext()) {
            Row r = it.next();
            System.out.println("Heade Loop Starts-->");
            headerId = r.getAttribute("HeaderId").toString();
            System.out.println("Heade Loop-->");
        }
        it.closeRowSetIterator();

        ViewObject linesVo = getLinePopUp1();
        linesVo.setWhereClause("HEADER_ID = " + headerId);
        System.out.println("heder id  --->" + headerId);
        linesVo.executeQuery();
        System.out.println("Lines----->starts");
        RowSetIterator itLines = linesVo.createRowSetIterator("linesIt");
        System.out.println("Lines----->starts2");
        while (itLines.hasNext()) {
            Row r = itLines.next();
            System.out.println("Lines Loop-->");
            populteLines(r);
            populteDetails(r);
        }
        itLines.closeRowSetIterator();
    }

    public Row createLines() {

        ViewObject vo = getMnjMfgWashRecipeLView1();
        Row row = vo.createRow();
        vo.insertRow(row);
        row.setNewRowState(Row.STATUS_INITIALIZED);
        return row;
    } //end of createHeader

    public Row createDetails() {
        ViewObject vo = getMnjMfgWashRecipeDView1();
        Row row = vo.createRow();
        vo.insertRow(row);
        row.setNewRowState(Row.STATUS_INITIALIZED);
        return row;
    } //end of createHeader

    public void populteLines(Row r) {

        Row lineRow = createLines();

        //        try {
        //            lineRow.setAttribute("LineId", r.getAttribute("LineId").toString());
        //
        //        } catch (Exception e) {
        //          ;
        //        }

        try {
            lineRow.setAttribute("MinorOperations",
                                 r.getAttribute("MinorOperations").toString());
        } catch (Exception e) {
            ;
        }
        try {
            lineRow.setAttribute("MajorOperations",
                                 r.getAttribute("MajorOperations").toString());
        } catch (Exception e) {
            ;
        }
        try {
            lineRow.setAttribute("Smv", r.getAttribute("Smv").toString());
        } catch (Exception e) {
            ;
        }
        try {
            lineRow.setAttribute("Temperature",
                                 r.getAttribute("Temperature").toString());
        } catch (Exception e) {
            ;
        }
        try {
            lineRow.setAttribute("Water", r.getAttribute("Water").toString());
        } catch (Exception e) {
            ;
        }
        try {
            lineRow.setAttribute("MinTime",
                                 r.getAttribute("MinTime").toString());
        } catch (Exception e) {
            ;
        }
    }

    public void populteDetails(Row r) {

        ViewObject detVo = getDetailPopUp1();
        detVo.setWhereClause("LINE_ID =" +
                             r.getAttribute("LineId").toString());
        detVo.executeQuery();

        RowSetIterator itDetails = detVo.createRowSetIterator("DIt");
        while (itDetails.hasNext()) {
            Row row = itDetails.next();
            Row detRow = createDetails();


            try {
                detRow.setAttribute("Uom", row.getAttribute("Uom").toString());
            } catch (Exception e) {
                ;
            }

            try {
                detRow.setAttribute("PerBatchQty",
                                    row.getAttribute("PerBatchQty").toString());
            } catch (Exception e) {
                ;
            }

            try {
                detRow.setAttribute("ItemCode",
                                    row.getAttribute("ItemCode").toString());
            } catch (Exception e) {
                ;
            }
            try {
                detRow.setAttribute("Description",
                                    row.getAttribute("Description").toString());
            } catch (Exception e) {
                ;
            }


        }
        itDetails.closeRowSetIterator();


    }


    /**
     * Container's getter for HederPopUp1.
     * @return HederPopUp1
     */
    public HederPopUpImpl getHederPopUp1() {
        return (HederPopUpImpl)findViewObject("HederPopUp1");
    }

    /**
     * Container's getter for LinePopUp1.
     * @return LinePopUp1
     */
    public LinePopUpImpl getLinePopUp1() {
        return (LinePopUpImpl)findViewObject("LinePopUp1");
    }

    /**
     * Container's getter for DetailPopUp1.
     * @return DetailPopUp1
     */
    public DetailPopUpImpl getDetailPopUp1() {
        return (DetailPopUpImpl)findViewObject("DetailPopUp1");
    }

    /**
     * Container's getter for PopulateOp1.
     * @return PopulateOp1
     */
    public PopulateOpImpl getPopulateOp1() {
        return (PopulateOpImpl)findViewObject("PopulateOp1");
    }

    /**
     * Container's getter for OperationsPopUpVO1.
     * @return OperationsPopUpVO1
     */
    public OperationsPopUpVOImpl getOperationsPopUpVO1() {
        return (OperationsPopUpVOImpl)findViewObject("OperationsPopUpVO1");
    }


    /// Code For Operations Pop - Up Sabih - 27-10-2016

    public void populateOperations() {


        ViewObject populatevo = getOperationsPopUpVO1(); // pop up view
        // populatevo.executeQuery();

        Row[] r = populatevo.getAllRowsInRange();
        System.out.println("Drop ------->" + r.length);
        for (Row row : r) {
            System.out.println("Flag Check--->" + row.getAttribute("Flag"));
            if (row.getAttribute("Flag") != null &&
                row.getAttribute("Flag").equals("Y")) {
                System.out.println("Flag --->" + row.getAttribute("Flag"));
                populateLinesOperations(row); /// method to populate dta
            }
        }
    }
    ////////////////////////////

    public void populateLinesOperations(Row poprow) {
        System.out.println("populateLinesTest ------->");

        ViewObject vo = getMnjMfgWashRecipeHView1();
        Integer NumberBatches;
        Integer PerBatchQuantity;

        try {
            NumberBatches =
                    Integer.parseInt(vo.getCurrentRow().getAttribute("NumberBatches").toString());
        } catch (Exception e) {
            // TODO: Add catch code
            NumberBatches = 0;
            e.printStackTrace();

        }

        try {
            PerBatchQuantity =
                    Integer.parseInt(vo.getCurrentRow().getAttribute("PerBatchQuantity").toString());

        } catch (Exception e) {
            // TODO: Add catch code
            PerBatchQuantity = 0;
            e.printStackTrace();
        }
        System.out.println("PerBatchQuantity is ..." + PerBatchQuantity);
        System.out.println("NumberBatches is ..." + NumberBatches);

        Row linerow = createLinesOperations(); // Line Creation
        linerow.setAttribute("MajorOperations",
                             getPopulateValue(poprow, "MajorOperation"));
        linerow.setAttribute("MinorOperations",
                             getPopulateValue(poprow, "MinorOperation"));
        linerow.setAttribute("Smv", getPopulateValue(poprow, "Sam"));

        linerow.setAttribute("NumberBatches", PerBatchQuantity);
        linerow.setAttribute("PerBatchQuantity", NumberBatches);


    } //end of populateLines

    public void popupSelectActionListener() {
        System.out.println("OK");
        ViewObject fillSize = getOperationsPopUpVO1();
        RowSetIterator fillSizeRowSetIterator =
            fillSize.createRowSetIterator("fillSizeRowSetIterator");
        while (fillSizeRowSetIterator.hasNext()) {
            Row row = fillSizeRowSetIterator.next();
            row.setAttribute("Flag", "Y");
            System.out.println("OK");
        }
        fillSizeRowSetIterator.closeRowSetIterator();
    }

    public void popupDeselectActionListener() {
        System.out.println("OK");
        ViewObject fillSize = getOperationsPopUpVO1();
        RowSetIterator fillSizeRowSetIterator =
            fillSize.createRowSetIterator("fillSizeRowSetIterator");
        while (fillSizeRowSetIterator.hasNext()) {
            Row row = fillSizeRowSetIterator.next();
            row.setAttribute("Flag", "N");
            System.out.println("OK");
        }
        fillSizeRowSetIterator.closeRowSetIterator();
    }

    public Row createLinesOperations() {

        ViewObject vo =
            getMnjMfgWashRecipeLView1(); // in which you wants to populate daa
        Row row = vo.createRow();
        vo.insertRow(row);
        row.setNewRowState(Row.STATUS_INITIALIZED);
        return row;
    } //end of createHeader


    /**
     * Container's getter for MnjMfgSubProcessVO1.
     * @return MnjMfgSubProcessVO1
     */
    public ViewObjectImpl getMnjMfgSubProcessVO1() {
        return (ViewObjectImpl)findViewObject("MnjMfgSubProcessVO1");
    }

    /**
     * Container's getter for MnjMfgWashRecSubProcFkLink1.
     * @return MnjMfgWashRecSubProcFkLink1
     */
    public ViewLinkImpl getMnjMfgWashRecSubProcFkLink1() {
        return (ViewLinkImpl)findViewLink("MnjMfgWashRecSubProcFkLink1");
    }

    /**
     * Container's getter for SubProcessPopUp1.
     * @return SubProcessPopUp1
     */
    public SubProcessPopUpImpl getSubProcessPopUp1() {
        return (SubProcessPopUpImpl)findViewObject("SubProcessPopUp1");
    }


    //// Sub - Process Pop - Up

    public void WhereClauseSubProcess() {
        System.out.println("WhereClauseSubProcess ------->");

        ViewObject vo = getMnjMfgWashRecipeLView1();
        Object MajorOperations =
            vo.getCurrentRow().getAttribute("MajorOperations");
        Object MinorOperations =
            vo.getCurrentRow().getAttribute("MinorOperations");


        ViewObject popVo = getSubProcessPopUp1();
        popVo.setWhereClause("MAJOR_OPERATIONS = '" + MajorOperations + "'" +
                             " AND MINOR_OPERATION = '" + MinorOperations +
                             "'");
        popVo.executeQuery();

    }


    public void populateSubProcess() {


        ViewObject populatevo = getSubProcessPopUp1(); // pop up view
        // populatevo.executeQuery();

        Row[] r = populatevo.getAllRowsInRange();
        System.out.println("Drop ------->" + r.length);
        for (Row row : r) {
            System.out.println("Selection Check--->" +
                               row.getAttribute("Selection"));
            if (row.getAttribute("Selection") != null &&
                row.getAttribute("Selection").equals("Y")) {
                System.out.println("Selection --->" +
                                   row.getAttribute("Selection"));
                populateLinesSubProcess(row); /// method to populate dta
            }
        }
    }
    ////////////////////////////

    public void populateLinesSubProcess(Row poprow) {
        System.out.println("SubProcess ------->");


        Row linerow = createLinesSubProcess(); // Line Creation
        linerow.setAttribute("SubProcess",
                             getPopulateValue(poprow, "SubProcess"));


    } //end of populateLines

    public Row createLinesSubProcess() {

        ViewObject vo =
            getMnjMfgSubProcessVO1(); // in which you wants to populate daa
        Row row = vo.createRow();
        vo.insertRow(row);
        row.setNewRowState(Row.STATUS_INITIALIZED);
        return row;
    } //end of createHeader


    /**
     * Container's getter for MnjMfgShadeLVO1.
     * @return MnjMfgShadeLVO1
     */
    public ViewObjectImpl getMnjMfgShadeLVO1() {
        return (ViewObjectImpl)findViewObject("MnjMfgShadeLVO1");
    }

    /**
     * Container's getter for MnjMfgWashRecipeShadeFkLink1.
     * @return MnjMfgWashRecipeShadeFkLink1
     */
    public ViewLinkImpl getMnjMfgWashRecipeShadeFkLink1() {
        return (ViewLinkImpl)findViewLink("MnjMfgWashRecipeShadeFkLink1");
    }

    // Version Creation


    public int VersionCreation() {

        int value = 0;

        ViewObject vo = getMnjMfgWashRecipeHView1();
        String HeaderId =
            vo.getCurrentRow().getAttribute("HeaderId").toString();
        //        String HeaderId = Integer.parseInt(vo.getCurrentRow().getAttribute("Name").toString()) ;

        System.out.println("HeaderId    " + HeaderId);

        String stmt =
            "BEGIN :1 := MNJ_WASHING_RECIPE.VERSION_CREATION(:2); end;";
        java.sql.CallableStatement cs =
            getDBTransaction().createCallableStatement(stmt, 1);
        int a = 0;
        try {
            cs.setString(2, HeaderId);
            cs.registerOutParameter(1, OracleTypes.INTEGER);
            cs.execute();
            value = cs.getInt(1);
            cs.close();
        } catch (Exception e) {
            //status = e.getMessage();
            ;
        }
        vo.executeQuery();
        //        System.out.println("Pass Fail value --------->>" + value);
        return value;


    }
    
    public int CopyCreation() {

        int value = 0;

        ViewObject vo = getMnjMfgWashRecipeHView1();
        String HeaderId =
            vo.getCurrentRow().getAttribute("HeaderId").toString();
        //        String HeaderId = Integer.parseInt(vo.getCurrentRow().getAttribute("Name").toString()) ;

        System.out.println("HeaderId    " + HeaderId);

        String stmt =
            "BEGIN :1 := MNJ_WASHING_RECIPE.COPY_CREATION(:2); end;";
        java.sql.CallableStatement cs =
            getDBTransaction().createCallableStatement(stmt, 1);
        int a = 0;
        try {
            cs.setString(2, HeaderId);
            cs.registerOutParameter(1, OracleTypes.INTEGER);
            cs.execute();
            value = cs.getInt(1);
            cs.close();
        } catch (Exception e) {
           System.out.println("=================================================      "+e.getMessage()); 
            
            ;
        }
        vo.executeQuery();
        //        System.out.println("Pass Fail value --------->>" + value);
        return value;


    }

    public void Delete_Header() {
        ViewObject vo = getMnjMfgWashRecipeHView1();
        String HeaderId =
            vo.getCurrentRow().getAttribute("HeaderId").toString();
        System.out.println("Recipe Header Id is ......" + HeaderId);
        Integer PHeaderId = Integer.parseInt(HeaderId);
        CallableStatement plSqlBlock = null;
        String Statement =
            "BEGIN DELETE FROM MNJ_MFG_WASH_RECIPE_H WHERE HEADER_ID = " +
            PHeaderId + ";" + "COMMIT; END;";
        plSqlBlock = getDBTransaction().createCallableStatement(Statement, 0);
        try {
            plSqlBlock.execute();
            vo.executeQuery();

        } catch (SQLException e) {
            e.printStackTrace();
        }
    }


    public void Copy_Fields_To_Lines(String PerBatchQty,
                                     String NumberOfBatches) {
        Commit();
        ViewObject vo = getMnjMfgWashRecipeHView1();
        ViewObject vol = getMnjMfgWashRecipeLView1();

        String HeaderId = null;


        try {
            HeaderId = vo.getCurrentRow().getAttribute("HeaderId").toString();
        } catch (Exception e) {
            // TODO: Add catch code
            HeaderId = null;
            e.printStackTrace();
        }


        System.out.println("Recipe Header Id is ......" + HeaderId);
        System.out.println("Number Batches is ......" + NumberOfBatches);
        System.out.println("Per Batch Quantity is ......" + PerBatchQty);


        if (vol.getRowCount() != 0) {
            System.out.println("In If... Lines Exist");
            Integer PHeaderId = Integer.parseInt(HeaderId);
            CallableStatement plSqlBlock = null;
            String Statement =
                "BEGIN update MNJ_MFG_WASH_RECIPE_L l set l.Number_Batches = " +
                NumberOfBatches + ",l.Per_Batch_Quantity =" + PerBatchQty +
                "where l.Header_ID= " + PHeaderId + ";" + "COMMIT; END;";
            plSqlBlock =
                    getDBTransaction().createCallableStatement(Statement, 0);
            try {
                plSqlBlock.execute();
                vo.executeQuery();

            } catch (SQLException e) {
                e.printStackTrace();
            }
        }

        else {
            System.out.println("In else... Lines Doesnot Exist");
        }
    }


    //    public void ReCalculate_Fields() {
    //
    //        ViewObject vol = getMnjMfgWashRecipeLView1();
    //        ViewObject vod = getMnjMfgWashRecipeDView1();
    //
    //        vol.executeQuery();
    //        vod.executeQuery();
    //
    //        for (Row row = vol.first(); row != null; row = vol.next()) {
    //            System.out.println("Number of times---"+row++);
    //        }
    //
    //
    //    }


    public void ReCalculate_Fields() {

        this.getDBTransaction().commit();

        double PerBatchWeight = 0.0;

        ViewObject hvo = this.getMnjMfgWashRecipeHView1();

        try {
            PerBatchWeight =
                    Double.parseDouble(hvo.getCurrentRow().getAttribute("PerBatchWeight").toString());
        } catch (Exception e) {
            PerBatchWeight = 0.0;
        }

        ViewObject lvo = this.getMnjMfgWashRecipeLView1();
        RowSetIterator lvoit = lvo.createRowSetIterator("lvoit");

        double Water = 0.00;
        double NumberBatches = 0.0;
        double PerBatchQuantity = 0.0;
        double Dosage = 0.0;
        double DosagePerc = 0.0;
        double PcsPerItem = 0.0;

        double PerBatchCons = 0.00;
        double TotalConsumption = 0.00;


        while (lvoit.hasNext()) {

            Row linesNext = lvoit.next();
            String PckassortLineid = null;
            try {
                PckassortLineid = linesNext.getAttribute("LineId").toString();
            } catch (Exception e) {
                ;
            }

            try {
                Water =
                        Double.parseDouble(linesNext.getAttribute("Water").toString());
                System.out.println("Water Value is... " + Water);
            } catch (Exception ee) {
                Water = 0.00;
                System.out.println("Exception Water");
            }

            try {
                NumberBatches =
                        Double.parseDouble(linesNext.getAttribute("NumberBatches").toString());
                System.out.println("Number Batches Value is... " + Water);
            } catch (Exception ee) {
                NumberBatches = 0.00;
                System.out.println("Exception Number Batches");
            }

            try {
                PerBatchQuantity =
                        Double.parseDouble(linesNext.getAttribute("PerBatchQuantity").toString());
                System.out.println("Per Batch Quantity Value is... " + Water);
            } catch (Exception ee) {
                NumberBatches = 0.00;
                System.out.println("Exception Per Batch Quantity");
            }

            RowSet DetailVO1it =
                (RowSet)linesNext.getAttribute("MnjMfgWashRecipeDView");

            while (DetailVO1it.hasNext()) {

                Row detailNext = DetailVO1it.next();

                try {
                    Dosage =
                            Double.parseDouble(detailNext.getAttribute("Dosage").toString());
                    System.out.println("Dosage Value is... " + Water);
                } catch (Exception ee) {
                    Dosage = 0.00;
                    System.out.println("Exception Dosage");
                }

                try {
                    DosagePerc =
                            Double.parseDouble(detailNext.getAttribute("DosagePerc").toString());
                    System.out.println("Dosage Percent Value is... " + Water);
                } catch (Exception ee) {
                    DosagePerc = 0.00;
                    System.out.println("Exception Dosage Percent");
                }


                try {
                    PcsPerItem =
                            Double.parseDouble(detailNext.getAttribute("PcsPerItem").toString());
                    System.out.println("Pcs Per Item Value is... " + Water);
                } catch (Exception ee) {
                    PcsPerItem = 0.00;
                    System.out.println("Exception Pcs Per Item");
                }

                if (Dosage != 0.0 && Water != 0.0) {
                    System.out.println("In if of Dosage.... PerBatchCons is ....." +
                                       PerBatchCons);
                    PerBatchCons = (Dosage * Water) / 1000;
                }

                if (PerBatchQuantity != 0.0 && PcsPerItem != 0.0) {
                    System.out.println("In if of PcsPerItem.... PerBatchCons is ....." +
                                       PerBatchCons);
                    PerBatchCons = PerBatchQuantity / PcsPerItem;
                }

                if (DosagePerc != 0.0 && PerBatchWeight != 0.0) {
                    System.out.println("In if of DosagePerc.... PerBatchCons is ....." +
                                       PerBatchCons);
                    PerBatchCons =
                            ((DosagePerc * PerBatchWeight) / 100) / 1000;
                }

                TotalConsumption = NumberBatches * PerBatchCons;

                System.out.println("PerBatchCons is ....." + PerBatchCons);
                System.out.println("TotalConsumption is ....." +
                                   TotalConsumption);

                detailNext.setAttribute("PerBatchCons", PerBatchCons);
                detailNext.setAttribute("TotalConsumption", TotalConsumption);

            }
            DetailVO1it.closeRowSetIterator();


        }
        lvoit.closeRowSetIterator();
        lvo.executeQuery();

        System.out.println("Save.....");

        this.getDBTransaction().commit();


    }


    public void setSessionValues(String orgId, String userId, String respId,
                                 String respAppl) {


        if (userId != null) {

            FacesContext fctx = FacesContext.getCurrentInstance();
            ExternalContext ectx = fctx.getExternalContext();
            HttpSession userSession = (HttpSession)ectx.getSession(false);
            userSession.setAttribute("userId", userId);
            userSession.setAttribute("orgId", orgId);
            userSession.setAttribute("respId", respId);
            userSession.setAttribute("respAppl", respAppl);
            userSession.setAttribute("unitName", getUnitName(orgId));
            userSession.setAttribute("userName", getUserName(userId));

        }
    }


    public String getUnitName(String orgId) {

        ViewObject vo = getoperatingUnitsVo1();
        vo.setWhereClause("ORGANIZATION_ID = " + orgId);
        vo.executeQuery();
        String name = null;
        vo.first();

        try {
            name = vo.getCurrentRow().getAttribute("Name").toString();
        } catch (Exception e) {
            // TODO: Add catch code
            e.printStackTrace();
        }
        return name;

    }

    public String getUserName(String userId) {

        ViewObject vo = getUsers_VO1();
        vo.setWhereClause("USER_ID = " + userId);
        vo.executeQuery();
        String Username = null;
        vo.first();

        try {
            Username = vo.getCurrentRow().getAttribute("UserName").toString();
        } catch (Exception e) {
            // TODO: Add catch code
            e.printStackTrace();
        }
        return Username;

    }

    public String validateIssueRecDate(){
        
            
            String DocumentDate = null;
            String recipeDocDate = null;
            String buyer = null;
            String style = null;
            String season = null;
            String color = null;
            String wash = null;
            Row row= null;
            
            ViewObject hvo = this.getMnjMfgWashRecipeHView1();
            row = hvo.getCurrentRow();
            try{
                recipeDocDate = row.getAttribute("DocDate").toString();
            }catch(NullPointerException e){
                recipeDocDate = null;    
            }
            try{
                buyer = row.getAttribute("CustomerName").toString();
            }catch(NullPointerException e){
                buyer = null;    
            }
            try{
                style = row.getAttribute("Style").toString();
            }catch(NullPointerException e){
                style = null;    
            }
            try{
                season = row.getAttribute("Season").toString();
            }catch(NullPointerException e){
                season = null;    
            }
            try{
                color = row.getAttribute("Color").toString();
            }catch(NullPointerException e){
                color = null;    
            }
            try{
                wash = row.getAttribute("WashName").toString();
            }catch(NullPointerException e){
                wash = null;    
            }
            System.out.println("recipeDocDate "+recipeDocDate);
            //ViewObject vo = this.getValidateDateIssueRecFrm1();
            String query = "SELECT DISTINCT NewHeaderEO.IR_HEADER_ID,NewHeaderEO.DOCUMENT_DATE, HeaderEO.ATTRIBUTE5 BUYER,  HeaderEO.STYLE_NAME, HeaderEO.SEASON, MNJ_ISSUE_REC_WASH_REC_L_EO.ATTRIBUTE3 COLOR FROM MNJ_MFG_WASH_IR_H NewHeaderEO,MNJ_MFG_ISSUE_REC_WASH_H HeaderEO,MNJ_ISSUE_REC_WASH_REC_L MNJ_ISSUE_REC_WASH_REC_L_EO WHERE   NewHeaderEO.IR_HEADER_ID = HeaderEO.IR_HEADER_ID AND     MNJ_ISSUE_REC_WASH_REC_L_EO.HEADER_ID = HeaderEO.HEADER_ID ORDER BY    NewHeaderEO.IR_HEADER_ID";
            ViewObject vo = createViewObjectFromQueryStmt("", query);
            vo.setWhereClause("BUYER ='"+buyer+"' AND STYLE_NAME='"+style+"' AND SEASON='"+season+"'AND COLOR ='"+color+"'");
            System.out.println(""+vo.getQuery());
            vo.executeQuery();
            row = vo.first();
            try{
                DocumentDate = row.getAttribute("DOCUMENT_DATE").toString();
            }
            catch(NullPointerException e){
                DocumentDate = null;
            }
            System.out.println("Document Date = "+DocumentDate);
            DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
            if(DocumentDate != null && recipeDocDate != null){
                try{
                    Date date1 = df.parse(DocumentDate);
                    System.out.println(date1);
                    Date date2 = df.parse(recipeDocDate);
                    System.out.println(date2);
                    if(DocumentDate != null && recipeDocDate != null){
                        if(date1.compareTo(date2) > 0){
                            System.out.println("asa");
                            showMessage("Document Date should be after Receipt Document Date.");
                            return "false";
                        }
                    }
                }catch (ParseException e) {
                    e.printStackTrace();
                    return "false";
                }
            }
            return "true";
    }
    
    public String showMessage(String messageText ) {
        //String messageText=”A prgramatic af:message”;
        FacesMessage fm = new FacesMessage(messageText);
        /**
         * set the type of the message.
         * Valid types: error, fatal,info,warning
         */
        fm.setSeverity(FacesMessage.SEVERITY_ERROR);
        FacesContext context = FacesContext.getCurrentInstance();
        context.addMessage(null, fm);
        return null;
    }
            


    public void Qty_Calculation() {
        getDBTransaction().commit();

        int b;
        ViewObject vo = getMnjMfgWashRecipeHView1();
        String Style = null;
        String BuyerID = null;
        String Season = null;
        String Wash = null;
        String Color = null;
        String systemid=null;
        try {
           systemid = vo.getCurrentRow().getAttribute("SystemId").toString();
        } catch (Exception e) {
            // TODO: Add catch code
            systemid = null;
            e.printStackTrace();
        }
/*
        try {
            Style = vo.getCurrentRow().getAttribute("Style").toString();
        } catch (Exception e) {
            // TODO: Add catch code
            Style = null;
            e.printStackTrace();
        }

        try {
            BuyerID = vo.getCurrentRow().getAttribute("CustomerId").toString();
        } catch (Exception e) {
            // TODO: Add catch code
            BuyerID = null;
            e.printStackTrace();
        }

        try {
            Season = vo.getCurrentRow().getAttribute("Season").toString();
        } catch (Exception e) {
            // TODO: Add catch code
            Season = null;
            e.printStackTrace();
        }

        try {
           
            Wash = vo.getCurrentRow().getAttribute("WashName").toString();
        } catch (Exception e) {
            // TODO: Add catch code
            Wash = null;
            e.printStackTrace();
        }

        try {
            Color = vo.getCurrentRow().getAttribute("Color").toString();
        } catch (Exception e) {
            // TODO: Add catch code
            Color = null;
            e.printStackTrace();
        }

        System.out.println("Parameters for Quantity are..............." +
                           Style + Season + BuyerID + Wash + Color+"  "+systemid);*/
        ViewObject populatevo = getQuanity_Calculation_VO1(); // Populate VO
        populatevo.setWhereClause(null);
        populatevo.clearCache();
       /* populatevo.setWhereClauseParam(0, Style);
        populatevo.setWhereClauseParam(1, Season);
        populatevo.setWhereClauseParam(2, BuyerID);
        populatevo.setWhereClauseParam(3, Color);
        populatevo.setWhereClauseParam(4, Wash);*/
       populatevo.setWhereClauseParam(0, systemid);
        populatevo.executeQuery();
        System.out.println(populatevo.getQuery());
        populatevo.first();
        System.out.println("Query @ calculation is..............." +
                           populatevo.getQuery());
        
        System.out.println(populatevo.getCurrentRow().getAttribute("Quantity"));
        populatevo.first();
      vo.getCurrentRow().setAttribute("Qty",
                                      populatevo.getCurrentRow().getAttribute("Quantity"));

        ViewObject populatevo1 = getFabric_Type_VO1(); // Populate VO
        populatevo1.setWhereClause(null);
      /*  populatevo1.setWhereClauseParam(0, BuyerID);
        populatevo1.setWhereClauseParam(1, Style);
        populatevo1.setWhereClauseParam(2, Season);
        populatevo1.setWhereClauseParam(3, Wash);
        populatevo1.setWhereClauseParam(4, Color);*/
      populatevo1.setWhereClauseParam(0, systemid);
        
        populatevo1.executeQuery();
        populatevo1.first();
        System.out.println("Query @ Fabric Type is..............." +
                           populatevo1.getQuery());

        populatevo1.first();
        String nullcondition = "-";
        if (populatevo1.getCurrentRow().getAttribute("FabricType") != null) {
            vo.getCurrentRow().setAttribute("FebricType",
                                            populatevo1.getCurrentRow().getAttribute("FabricType"));

        } else {
            vo.getCurrentRow().setAttribute("FebricType", nullcondition);
        }
        getDBTransaction().commit();
       

    } //populate Lines


    public void Fabric_Type_H() {
        getDBTransaction().commit();

        int b;
        ViewObject vo = getMnjMfgWashRecipeHView1();
        String Style = null;
        String BuyerID = null;
        String Season = null;
        String Wash = null;
        String Color = null;

        try {
            Style = vo.getCurrentRow().getAttribute("Style").toString();
        } catch (Exception e) {
            // TODO: Add catch code
            Style = null;
            e.printStackTrace();
        }

        try {
            BuyerID = vo.getCurrentRow().getAttribute("CustomerId").toString();
        } catch (Exception e) {
            // TODO: Add catch code
            BuyerID = null;
            e.printStackTrace();
        }

        try {
            Season = vo.getCurrentRow().getAttribute("Season").toString();
        } catch (Exception e) {
            // TODO: Add catch code
            Season = null;
            e.printStackTrace();
        }

        try {
            Wash = vo.getCurrentRow().getAttribute("Wash").toString();
        } catch (Exception e) {
            // TODO: Add catch code
            Wash = null;
            e.printStackTrace();
        }

        try {
            Color = vo.getCurrentRow().getAttribute("Color").toString();
        } catch (Exception e) {
            // TODO: Add catch code
            Color = null;
            e.printStackTrace();
        }

        System.out.println("Parameters for Fabric Type are..............." +
                           Style + Season + BuyerID + Wash + Color);
        ViewObject populatevo = getFabric_Type_VO1(); // Populate VO
        populatevo.setWhereClause(null);
        populatevo.setWhereClauseParam(0, BuyerID);
        populatevo.setWhereClauseParam(1, Style);
        populatevo.setWhereClauseParam(2, Season);
        populatevo.setWhereClauseParam(3, Wash);
        populatevo.setWhereClauseParam(4, Color);
        populatevo.executeQuery();
        populatevo.first();
        System.out.println("Query @ Fabric Type is..............." +
                           populatevo.getQuery());

        populatevo.first();
        vo.getCurrentRow().setAttribute("FebricType",
                                        populatevo.getCurrentRow().getAttribute("FabricType"));
        getDBTransaction().commit();
       
    }

    protected Object callStoredFunction(int sqlReturnType, String stmt,
                                        Object[] bindVars) {
        CallableStatement st = null;
        try {
            // 1. Create a JDBC CallabledStatement
            st =
 getDBTransaction().createCallableStatement("begin ? := " + stmt + ";end;", 0);
            // 2. Register the first bind variable for the return value
            st.registerOutParameter(1, sqlReturnType);
            if (bindVars != null) {
                // 3. Loop over values for the bind variables passed in, if any
                for (int z = 0; z < bindVars.length; z++) {
                    // 4. Set the value of user-supplied bind vars in the stmt
                    st.setObject(z + 2, bindVars[z]);
                }
            }
            // 5. Set the value of user-supplied bind vars in the stmt
            st.executeUpdate();
            // 6. Return the value of the first bind variable
            return st.getObject(1);

        } catch (SQLException e) {
            throw new JboException(e);
        } finally {
            if (st != null) {
                try {
                    // 7. Close the statement
                    st.close();
                } catch (SQLException e) {
                    ;
                }
            }
        }

    }

    public void DeleteOperations() {

        getDBTransaction().commit();

        String Style = null;
        String Season = null;
        String Buyer = null;
        String Wash = null;
        String Color = null;

        String HeaderId = null;
        System.out.println("In method DeleteOperations.....");
        ViewObject voh = getMnjMfgWashRecipeHView1();

        try {

            try {
                Style =
                        voh.getCurrentRow().getAttribute("Style").toString();
            } catch (Exception e) {
                // TODO: Add catch code
                Style = null;
                e.printStackTrace();
            }

            try {
                Season = voh.getCurrentRow().getAttribute("Season").toString();
            } catch (Exception e) {
                // TODO: Add catch code
                Season = null;
                e.printStackTrace();
            }

            try {
                Buyer =
                        voh.getCurrentRow().getAttribute("CustomerId").toString();
            } catch (Exception e) {
                // TODO: Add catch code
                Buyer = null;
                e.printStackTrace();
            }

            try {
                Wash = voh.getCurrentRow().getAttribute("WashName").toString();
            } catch (Exception e) {
                // TODO: Add catch code
                Wash = null;
                e.printStackTrace();
            }

            try {
                Color = voh.getCurrentRow().getAttribute("Color").toString();
            } catch (Exception e) {
                // TODO: Add catch code
                Color = null;
                e.printStackTrace();
            }

            System.out.println("Parameters are.... " + Style + Season + Buyer +
                               Wash + Color);

            ViewObject vo = getMnjMfgWashRecipeLView1();
            MnjMfgWashRecipeLViewRowImpl HeaderRow =
                (MnjMfgWashRecipeLViewRowImpl)vo.getCurrentRow();

            try {
                HeaderId = HeaderRow.getLineId().toString();
            } catch (Exception e) {
                // TODO: Add catch code
                HeaderId = null;
                e.printStackTrace();
            }

            if (CheckOperations(Buyer, Style, Season, Wash, Color) == 1) {
                FacesContext context = FacesContext.getCurrentInstance();
                FacesMessage message =
                    new FacesMessage(FacesMessage.SEVERITY_ERROR,
                                     "Can not delete record as data exist (Buyer, Style, Season, Wash, Color) on Washing Operation Plan .",
                                     "");
                //new FacesMessage("Delivery Size Quantity should not be greater than Delivery Quantity...");
                context.addMessage(null, message);
            } else {


                System.out.println("Header Id is ......" + HeaderId);
                Integer PHeaderId = Integer.parseInt(HeaderId);
                CallableStatement plSqlBlock = null;
                String Statement =
                    "BEGIN DELETE FROM MNJ_MFG_WASH_RECIPE_L WHERE LINE_ID = " +
                    PHeaderId + ";" + "COMMIT; END;";
                plSqlBlock =
                        getDBTransaction().createCallableStatement(Statement,
                                                                   0);
                try {
                    plSqlBlock.execute();
                    vo.executeQuery();

                } catch (SQLException e) {
                    e.printStackTrace();
                }


                FacesContext context = FacesContext.getCurrentInstance();
                FacesMessage message = new FacesMessage("Record Deleted...");
                context.addMessage(null, message);
            }


        } catch (Exception e) {
            // TODO: Add catch code

            e.printStackTrace();
        }


        getDBTransaction().commit();

    }

    public int CheckOperations(String BuyerId, String Style, String Season,
                               String Wash, String Color) {

        Map sessionScope = ADFContext.getCurrent().getSessionScope();

        String orgId;
        
        // orgId = (String)sessionScope.get("orgId");
        orgId = this.getMnjMfgWashRecipeHView1().getCurrentRow().getAttribute("OrgId").toString();

        int count = 0;
        count =
                (Integer)callStoredFunction(INTEGER, "mnj_washing_delete_validation.check_recipe_lines(?, ?, ?, ?, ?, ?)",
                                            new Object[] { Integer.parseInt(orgId),
                                                           BuyerId, Style,
                                                           Season, Wash,
                                                           Color });

        return count;
    }

    public void DeleteChemicals() {

        getDBTransaction().commit();

        String Style = null;
        String Season = null;
        String Buyer = null;
        String Wash = null;
        String Color = null;

        String HeaderId = null;
        System.out.println("In method DeleteChemicals.....");
        ViewObject voh = getMnjMfgWashRecipeHView1();

        try {

            try {
                Style =
                        voh.getCurrentRow().getAttribute("Style").toString();
            } catch (Exception e) {
                // TODO: Add catch code
                Style = null;
                e.printStackTrace();
            }

            try {
                Season = voh.getCurrentRow().getAttribute("Season").toString();
            } catch (Exception e) {
                // TODO: Add catch code
                Season = null;
                e.printStackTrace();
            }

            try {
                Buyer =
                        voh.getCurrentRow().getAttribute("CustomerId").toString();
            } catch (Exception e) {
                // TODO: Add catch code
                Buyer = null;
                e.printStackTrace();
            }

            try {
                Wash = voh.getCurrentRow().getAttribute("WashName").toString();
            } catch (Exception e) {
                // TODO: Add catch code
                Wash = null;
                e.printStackTrace();
            }

            try {
                Color = voh.getCurrentRow().getAttribute("Color").toString();
            } catch (Exception e) {
                // TODO: Add catch code
                Color = null;
                e.printStackTrace();
            }

            System.out.println("Parameters are....  Style  " + Style+"Season   " + Season +"Buyer    "+ Buyer +"Wash   "+Wash +"Color   " +Color);

            ViewObject vo = getMnjMfgWashRecipeDView1();
            MnjMfgWashRecipeDViewRowImpl HeaderRow =
                (MnjMfgWashRecipeDViewRowImpl)vo.getCurrentRow();

            try {
                HeaderId = HeaderRow.getDetailId().toString();
            } catch (Exception e) {
                // TODO: Add catch code
                HeaderId = null;
                e.printStackTrace();
            }

            if (CheckChemicals(Buyer, Style, Season, Wash, Color) == 1) {
            
               System.out.println(" CheckChemicals(Buyer, Style, Season, Wash, Color) == 1)              ");
            
                FacesContext context = FacesContext.getCurrentInstance();
                FacesMessage message =
                    new FacesMessage(FacesMessage.SEVERITY_ERROR,
                                     "Can not delete record as data exist (Buyer, Style, Season, Wash, Color) on Washing Operation Plan ",
                                     "");
                context.addMessage(null, message);
            } else {
                
                
                

                System.out.println("Header Id is ......" + HeaderId);
                Integer PHeaderId = Integer.parseInt(HeaderId);
                CallableStatement plSqlBlock = null;
                String Statement =
                    "BEGIN DELETE FROM MNJ_MFG_WASH_RECIPE_D WHERE DETAIL_ID = " +
                    PHeaderId + ";" + "COMMIT; END;";
                plSqlBlock =
                        getDBTransaction().createCallableStatement(Statement,
                                                                   0);
                try {
                    plSqlBlock.execute();
                    vo.executeQuery();

                } catch (SQLException e) {
                    e.printStackTrace();
                }


                FacesContext context = FacesContext.getCurrentInstance();
                FacesMessage message = new FacesMessage("Record Deleted...");
                context.addMessage(null, message);
            }


        } catch (Exception e) {
            // TODO: Add catch code

            e.printStackTrace();
        }


        getDBTransaction().commit();

    }

    public int CheckChemicals(String BuyerId, String Style, String Season,
                              String Wash, String Color) {

        Map sessionScope = ADFContext.getCurrent().getSessionScope();
        
        
        String orgId;
        
        // orgId = (String)sessionScope.get("orgId");
        orgId = this.getMnjMfgWashRecipeHView1().getCurrentRow().getAttribute("OrgId").toString();
        
        System.out.println("Org ID is...." + orgId);

        int count = 0;
        count =
                (Integer)callStoredFunction(INTEGER, "mnj_washing_delete_validation.check_recipe_chemicals(?, ?, ?, ?, ?, ?)",
                                            new Object[] { Integer.parseInt(orgId),
                                                           BuyerId, Style,
                                                           Season, Wash,
                                                           Color });

        return count;
    }

    public void DeleteSubProcess() {

        getDBTransaction().commit();

        String Style = null;
        String Season = null;
        String Buyer = null;
        String Wash = null;
        String Color = null;

        String HeaderId = null;
        System.out.println("In method DeleteSubProcess.....");
        ViewObject voh = getMnjMfgWashRecipeHView1();

        try {

            try {
                Style =
                        voh.getCurrentRow().getAttribute("Style").toString();
            } catch (Exception e) {
                // TODO: Add catch code
                Style = null;
                e.printStackTrace();
            }

            try {
                Season = voh.getCurrentRow().getAttribute("Season").toString();
            } catch (Exception e) {
                // TODO: Add catch code
                Season = null;
                e.printStackTrace();
            }

            try {
                Buyer =
                        voh.getCurrentRow().getAttribute("CustomerId").toString();
            } catch (Exception e) {
                // TODO: Add catch code
                Buyer = null;
                e.printStackTrace();
            }

            try {
                Wash = voh.getCurrentRow().getAttribute("WashName").toString();
            } catch (Exception e) {
                // TODO: Add catch code
                Wash = null;
                e.printStackTrace();
            }

            try {
                Color = voh.getCurrentRow().getAttribute("Color").toString();
            } catch (Exception e) {
                // TODO: Add catch code
                Color = null;
                e.printStackTrace();
            }

            System.out.println("Parameters are.... " + Style + Season + Buyer +
                               Wash + Color);

            ViewObject vo = getMnjMfgSubProcessVO1();
            MnjMfgSubProcessVORowImpl HeaderRow =
                (MnjMfgSubProcessVORowImpl)vo.getCurrentRow();

            try {
                HeaderId = HeaderRow.getSubDetailId().toString();
            } catch (Exception e) {
                // TODO: Add catch code
                HeaderId = null;
                e.printStackTrace();
            }

            if (CheckSubProcess(Buyer, Style, Season, Wash, Color) == 1) {
                FacesContext context = FacesContext.getCurrentInstance();
                FacesMessage message =
                    new FacesMessage(FacesMessage.SEVERITY_ERROR,
                                     "Can not delete record as data exist on prior forms....",
                                     "");
                context.addMessage(null, message);
            } else {
                System.out.println("Header Id is ......" + HeaderId);
                Integer PHeaderId = Integer.parseInt(HeaderId);
                CallableStatement plSqlBlock = null;
                String Statement =
                    "BEGIN DELETE FROM MNJ_MFG_WASH_RECIPE_SUB_PROC WHERE SUB_DETAIL_ID = " +
                    PHeaderId + ";" + "COMMIT; END;";
                plSqlBlock =
                        getDBTransaction().createCallableStatement(Statement,
                                                                   0);
                try {
                    plSqlBlock.execute();
                    vo.executeQuery();

                } catch (SQLException e) {
                    e.printStackTrace();
                }
                FacesContext context = FacesContext.getCurrentInstance();
                FacesMessage message = new FacesMessage("Record Deleted...");
                context.addMessage(null, message);
            }
        } catch (Exception e) {
            // TODO: Add catch code

            e.printStackTrace();
        }
        getDBTransaction().commit();

    }

    public int CheckSubProcess(String BuyerId, String Style, String Season,
                               String Wash, String Color) {

        Map sessionScope = ADFContext.getCurrent().getSessionScope();

        String orgId = (String)sessionScope.get("orgId");
        System.out.println("Org ID is...." + orgId);

        int count = 0;
        count =
                (Integer)callStoredFunction(INTEGER, "mnj_washing_delete_validation.check_recipe_subprocess(?, ?, ?, ?, ?, ?)",
                                            new Object[] { Integer.parseInt(orgId),
                                                           BuyerId, Style,
                                                           Season, Wash,
                                                           Color });

        return count;
    }


    /**
     * Container's getter for operatingUnitsVo1.
     * @return operatingUnitsVo1
     */
    public ViewObjectImpl getoperatingUnitsVo1() {
        return (ViewObjectImpl)findViewObject("operatingUnitsVo1");
    }

    /**
     * Container's getter for Users_VO1.
     * @return Users_VO1
     */
    public ViewObjectImpl getUsers_VO1() {
        return (ViewObjectImpl)findViewObject("Users_VO1");
    }

    /**
     * Container's getter for Quanity_Calculation_VO1.
     * @return Quanity_Calculation_VO1
     */
    public ViewObjectImpl getQuanity_Calculation_VO1() {
        return (ViewObjectImpl)findViewObject("Quanity_Calculation_VO1");
    }

    /**
     * Container's getter for Fabric_Type_VO1.
     * @return Fabric_Type_VO1
     */
    public ViewObjectImpl getFabric_Type_VO1() {
        return (ViewObjectImpl)findViewObject("Fabric_Type_VO1");
    }

    /**
     * Container's getter for ValidateDateIssueRecFrm1.
     * @return ValidateDateIssueRecFrm1
     */
    public ViewObjectImpl getValidateDateIssueRecFrm1() {
        return (ViewObjectImpl)findViewObject("ValidateDateIssueRecFrm1");
    }

    /**
     * Container's getter for WashRecipeHValidateVL1.
     * @return WashRecipeHValidateVL1
     */
    public ViewLinkImpl getWashRecipeHValidateVL1() {
        return (ViewLinkImpl)findViewLink("WashRecipeHValidateVL1");
    }

    /**
     * Container's getter for ValidateDateIssueRecFrm2.
     * @return ValidateDateIssueRecFrm2
     */
    public ViewObjectImpl getValidateDateIssueRecFrm2() {
        return (ViewObjectImpl)findViewObject("ValidateDateIssueRecFrm2");
    }
} //End of AM
