package mnj.mfg.model.lov.views;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Oct 27 13:24:59 BDT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class OperationsPopUpVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public OperationsPopUpVOImpl() {
    }
}
